// Club.java
package presentation;

public enum Club {
    NOBLEARTPEPIEUXOIS,
    CARCASSONNEBOXING,
    BCNARBONNAIS,
    BCARIEGEOIS,
    NIMESBOXE,
    BOXINGCLUBEBAM,
    BOXINGCLUBALESIEN,
    CAHORSBOXE,
    BCTOULOUSAIN,
    SPORTINGBOXECUGNAUX,
    BLAGNACBOXINGCLUB,
    BOXINGCLUBBAGATELLE,
    BOXINGCLUBROQUETTOIS,
    BOXINGCLUBAUTERIVAIN,
    BOXINGCLUBMURET,
    SAINTLYSOLYMPIQUEBOXE,
    BOXINGCENTERTOULOUSE,
    BCALBIGEOIS,
    BCCASTRAISTARNSUD,
    BCMONTPELLIERAIN,
    BOXINGCLUBALDOASARO,
    BCMARCELCERDANBEZIERS
}